-- Dispatch v2 Phase 3 reliability helpers
-- Run this in Supabase SQL Editor for the sandbox project before load testing.

create table if not exists public.dispatch_audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  actor text,
  order_id text,
  route_id text,
  message text,
  before_json jsonb,
  after_json jsonb,
  created_at timestamptz not null default now()
);

create index if not exists dispatch_audit_log_created_at_idx
  on public.dispatch_audit_log (created_at desc);

create index if not exists dispatch_audit_log_order_id_idx
  on public.dispatch_audit_log (order_id);

create index if not exists dispatch_audit_log_route_id_idx
  on public.dispatch_audit_log (route_id);

create index if not exists dispatch_orders_active_board_idx
  on public.dispatch_orders (status, delivery_status, requested_window, created_at);

create index if not exists dispatch_orders_route_sequence_idx
  on public.dispatch_orders (assigned_route_id, stop_sequence, created_at)
  where assigned_route_id is not null;

create index if not exists dispatch_orders_order_number_idx
  on public.dispatch_orders (order_number);

create index if not exists dispatch_orders_updated_created_idx
  on public.dispatch_orders (updated_at desc, created_at desc);

create index if not exists dispatch_orders_status_updated_idx
  on public.dispatch_orders (status, updated_at desc);

create index if not exists dispatch_orders_delivery_status_delivered_idx
  on public.dispatch_orders (delivery_status, delivered_at desc, updated_at desc);

create index if not exists dispatch_orders_assigned_status_idx
  on public.dispatch_orders (assigned_route_id, status, delivery_status)
  where assigned_route_id is not null;

create extension if not exists pg_trgm;

create index if not exists dispatch_orders_order_number_trgm_idx
  on public.dispatch_orders using gin (order_number gin_trgm_ops);

create index if not exists dispatch_orders_customer_trgm_idx
  on public.dispatch_orders using gin (customer gin_trgm_ops);

create index if not exists dispatch_orders_contact_trgm_idx
  on public.dispatch_orders using gin (contact gin_trgm_ops);

create index if not exists dispatch_orders_address_trgm_idx
  on public.dispatch_orders using gin (address gin_trgm_ops);

create index if not exists dispatch_orders_city_trgm_idx
  on public.dispatch_orders using gin (city gin_trgm_ops);

create index if not exists dispatch_orders_material_trgm_idx
  on public.dispatch_orders using gin (material gin_trgm_ops);

create index if not exists dispatch_orders_requested_window_trgm_idx
  on public.dispatch_orders using gin (requested_window gin_trgm_ops);

create index if not exists dispatch_routes_active_code_idx
  on public.dispatch_routes (is_active, code);

create extension if not exists pgcrypto;

create table if not exists public.dispatch_trucks (
  id text primary key default gen_random_uuid()::text,
  truck_number text not null unique,
  name text,
  tons numeric not null default 22,
  yards numeric not null default 30,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.dispatch_trucks
  add column if not exists id text default gen_random_uuid()::text,
  add column if not exists truck_number text,
  add column if not exists name text,
  add column if not exists tons numeric not null default 22,
  add column if not exists yards numeric not null default 30,
  add column if not exists is_active boolean not null default true,
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

alter table public.dispatch_trucks
  alter column id set default gen_random_uuid()::text;

update public.dispatch_trucks
set id = gen_random_uuid()::text
where id is null or id = '';

alter table public.dispatch_trucks
  alter column id set not null;

update public.dispatch_trucks
set truck_number = coalesce(nullif(truck_number, ''), nullif(name, ''), id)
where truck_number is null or truck_number = '';

alter table public.dispatch_trucks
  alter column truck_number set not null;

create index if not exists dispatch_trucks_active_number_idx
  on public.dispatch_trucks (is_active, truck_number);

create index if not exists dispatch_trucks_number_lower_idx
  on public.dispatch_trucks (lower(truck_number));

create or replace function public.set_dispatch_trucks_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists dispatch_trucks_set_updated_at on public.dispatch_trucks;
create trigger dispatch_trucks_set_updated_at
  before update on public.dispatch_trucks
  for each row execute function public.set_dispatch_trucks_updated_at();

create table if not exists public.dispatch_b2b_companies (
  id text primary key,
  shopify_company_id text not null,
  shopify_company_contact_id text,
  shopify_location_id text,
  company_name text not null,
  contractor_tier text not null default 'tier1',
  catalog_titles text[] not null default '{}'::text[],
  contact_name text,
  email text,
  phone text,
  billing_address1 text,
  billing_address2 text,
  billing_city text,
  billing_province text,
  billing_postal_code text,
  billing_country text default 'US',
  tax_exempt boolean not null default false,
  payment_terms_name text,
  payment_terms_template_id text,
  payment_terms_due_in_days integer,
  raw_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.dispatch_b2b_companies
  add column if not exists shopify_company_id text,
  add column if not exists shopify_company_contact_id text,
  add column if not exists shopify_location_id text,
  add column if not exists company_name text,
  add column if not exists contractor_tier text not null default 'tier1',
  add column if not exists catalog_titles text[] not null default '{}'::text[],
  add column if not exists contact_name text,
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists billing_address1 text,
  add column if not exists billing_address2 text,
  add column if not exists billing_city text,
  add column if not exists billing_province text,
  add column if not exists billing_postal_code text,
  add column if not exists billing_country text default 'US',
  add column if not exists tax_exempt boolean not null default false,
  add column if not exists payment_terms_name text,
  add column if not exists payment_terms_template_id text,
  add column if not exists payment_terms_due_in_days integer,
  add column if not exists raw_json jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

update public.dispatch_b2b_companies
set id = coalesce(nullif(id, ''), nullif(shopify_location_id, ''), shopify_company_id)
where id is null or id = '';

create index if not exists dispatch_b2b_companies_company_name_idx
  on public.dispatch_b2b_companies (company_name);

create index if not exists dispatch_b2b_companies_shopify_company_idx
  on public.dispatch_b2b_companies (shopify_company_id);

create index if not exists dispatch_b2b_companies_shopify_company_contact_idx
  on public.dispatch_b2b_companies (shopify_company_contact_id);

create index if not exists dispatch_b2b_companies_contractor_tier_idx
  on public.dispatch_b2b_companies (contractor_tier);

create index if not exists dispatch_b2b_companies_payment_terms_template_idx
  on public.dispatch_b2b_companies (payment_terms_template_id);

create or replace function public.set_dispatch_b2b_companies_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists dispatch_b2b_companies_set_updated_at on public.dispatch_b2b_companies;
create trigger dispatch_b2b_companies_set_updated_at
  before update on public.dispatch_b2b_companies
  for each row execute function public.set_dispatch_b2b_companies_updated_at();

alter table public.custom_delivery_quotes
  add column if not exists company_name text,
  add column if not exists shopify_company_id text,
  add column if not exists shopify_company_contact_id text,
  add column if not exists shopify_company_location_id text,
  add column if not exists payment_terms_name text,
  add column if not exists payment_terms_template_id text,
  add column if not exists payment_terms_due_in_days integer,
  add column if not exists tax_exempt boolean not null default false,
  add column if not exists billing_address1 text,
  add column if not exists billing_address2 text,
  add column if not exists billing_city text,
  add column if not exists billing_province text,
  add column if not exists billing_postal_code text,
  add column if not exists billing_country text default 'US';

create index if not exists custom_delivery_quotes_company_name_idx
  on public.custom_delivery_quotes (company_name);

create index if not exists custom_delivery_quotes_payment_terms_template_idx
  on public.custom_delivery_quotes (payment_terms_template_id);

create table if not exists public.dispatch_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists dispatch_settings_updated_at_idx
  on public.dispatch_settings (updated_at desc);

create table if not exists public.dispatch_stop_metrics (
  order_id text primary key references public.dispatch_orders(id) on delete cascade,
  route_id text references public.dispatch_routes(id) on delete set null,
  route_code text,
  order_number text,
  driver_id text,
  driver_name text,
  truck text,
  customer text,
  city text,
  material text,
  quantity numeric,
  unit text,
  stop_sequence integer,
  google_round_trip_minutes numeric,
  google_round_trip_miles numeric,
  google_one_way_minutes numeric,
  enroute_at timestamptz,
  delivered_at timestamptz,
  actual_drive_minutes numeric,
  actual_round_trip_estimate_minutes numeric,
  correction_factor numeric,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists dispatch_stop_metrics_route_idx
  on public.dispatch_stop_metrics (route_id, stop_sequence asc);

create index if not exists dispatch_stop_metrics_driver_city_idx
  on public.dispatch_stop_metrics (driver_name, city);

create index if not exists dispatch_stop_metrics_delivered_at_idx
  on public.dispatch_stop_metrics (delivered_at desc)
  where delivered_at is not null;

create or replace function public.set_dispatch_stop_metrics_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists dispatch_stop_metrics_set_updated_at on public.dispatch_stop_metrics;

create trigger dispatch_stop_metrics_set_updated_at
before update on public.dispatch_stop_metrics
for each row
execute function public.set_dispatch_stop_metrics_updated_at();

create table if not exists public.dispatch_driver_locations (
  route_id text primary key references public.dispatch_routes(id) on delete cascade,
  route_code text,
  driver_id text,
  driver_name text,
  truck text,
  latitude double precision not null,
  longitude double precision not null,
  accuracy numeric,
  heading numeric,
  speed numeric,
  captured_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Existing sandbox databases may already have this table from an earlier
-- version. `create table if not exists` will not add new columns, so keep the
-- live-tracking shape upgraded in place.
alter table public.dispatch_driver_locations
  add column if not exists route_id text;

alter table public.dispatch_driver_locations
  add column if not exists route_code text;

alter table public.dispatch_driver_locations
  add column if not exists driver_id text;

alter table public.dispatch_driver_locations
  add column if not exists driver_name text;

alter table public.dispatch_driver_locations
  add column if not exists truck text;

alter table public.dispatch_driver_locations
  add column if not exists accuracy numeric;

alter table public.dispatch_driver_locations
  add column if not exists heading numeric;

alter table public.dispatch_driver_locations
  add column if not exists speed numeric;

alter table public.dispatch_driver_locations
  add column if not exists captured_at timestamptz default timezone('utc', now());

alter table public.dispatch_driver_locations
  add column if not exists updated_at timestamptz default timezone('utc', now());

create extension if not exists pgcrypto;

do $$
declare
  existing_id_type text;
begin
  select data_type
    into existing_id_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'dispatch_driver_locations'
    and column_name = 'id';

  if existing_id_type = 'uuid' then
    execute 'alter table public.dispatch_driver_locations alter column id set default gen_random_uuid()';
  elsif existing_id_type in ('text', 'character varying') then
    execute 'alter table public.dispatch_driver_locations alter column id set default gen_random_uuid()::text';
  elsif existing_id_type in ('bigint', 'integer') then
    execute 'create sequence if not exists public.dispatch_driver_locations_id_seq';
    execute 'alter table public.dispatch_driver_locations alter column id set default nextval(''public.dispatch_driver_locations_id_seq'')';
  end if;
end $$;

update public.dispatch_driver_locations
set
  captured_at = coalesce(captured_at, timezone('utc', now())),
  updated_at = coalesce(updated_at, timezone('utc', now()))
where captured_at is null
   or updated_at is null;

delete from public.dispatch_driver_locations old_location
using public.dispatch_driver_locations newer_location
where old_location.route_id = newer_location.route_id
  and old_location.route_id is not null
  and old_location.ctid < newer_location.ctid;

create unique index if not exists dispatch_driver_locations_route_id_uidx
  on public.dispatch_driver_locations (route_id);

create index if not exists dispatch_driver_locations_updated_at_idx
  on public.dispatch_driver_locations (updated_at desc);

create index if not exists dispatch_driver_locations_driver_idx
  on public.dispatch_driver_locations (driver_id, updated_at desc);

create table if not exists public.dispatch_user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  role text not null default 'viewer',
  permissions text[] not null default array[]::text[],
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists dispatch_user_roles_email_idx
  on public.dispatch_user_roles (lower(email));

create index if not exists dispatch_user_roles_active_idx
  on public.dispatch_user_roles (is_active, role);

create or replace function public.set_dispatch_user_roles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists dispatch_user_roles_set_updated_at on public.dispatch_user_roles;

create trigger dispatch_user_roles_set_updated_at
before update on public.dispatch_user_roles
for each row
execute function public.set_dispatch_user_roles_updated_at();

-- Ask Supabase/PostgREST to refresh its schema cache after adding columns.
notify pgrst, 'reload schema';
