import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/board.tsx"),
  route("login", "routes/login.tsx"),
  route("calendar", "routes/calendar.tsx"),
  route("allotment", "routes/allotment.tsx"),
  route("driver", "routes/driver.tsx"),
  route("loader", "routes/loader.tsx"),
  route("monitor", "routes/monitor.tsx"),
  route("map", "routes/map.tsx"),
  route("imports", "routes/imports.tsx"),
  route("quote", "routes/quote.tsx"),
  route("custom-quote", "routes/custom-quote.tsx"),
  route("quote-review", "routes/quote-review.tsx"),
  route("updates", "routes/updates.tsx"),
  route("timing", "routes/timing.tsx"),
  route("audit", "routes/audit.tsx"),
  route("orders", "routes/orders.tsx"),
  route("delivered", "routes/delivered.tsx"),
  route("routes", "routes/routes.tsx"),
  route("trucks", "routes/trucks.tsx"),
  route("settings", "routes/settings.tsx"),
  route("api/shopify-import", "routes/api.shopify-import.ts"),
  route("api/shopify-import-new", "routes/api.shopify-import-new.ts"),
  route("api/create-draft-order", "routes/api.create-draft-order.ts"),
  route("api/update-quote", "routes/api.update-quote.ts"),
  route("api/delete-quote", "routes/api.delete-quote.ts"),
  route("api/calculate-distances", "routes/api.calculate-distances.ts"),
  route("api/driver-location", "routes/api.driver-location.ts"),
  route("setup-status", "routes/setup-status.ts"),
  route("health", "routes/health.ts"),
] satisfies RouteConfig;
